list_response_stub = [{'album_name': 'STAY (with Justin Bieber)',
  'artist_name': 'Justin Bieber',
  'music_id': '5HCyWlXZPP0y6Gqq8TgA20',
  'music_name': 'STAY (with Justin Bieber)'},
 {'album_name': "Harry's House",
  'artist_name': 'Harry Styles',
  'music_id': '4Dvkj6JhhA12EX05fT7y2e',
  'music_name': 'As It Was'},
 {'album_name': 'Dawn FM',
  'artist_name': 'The Weeknd',
  'music_id': '1nH2PkJL1XoUq8oE6tBZoU',
  'music_name': 'Sacrifice'},
 {'album_name': 'One Right Now',
  'artist_name': 'The Weeknd',
  'music_id': '00Blm7zeNqgYLPtW6zg8cj',
  'music_name': 'One Right Now (with The Weeknd)'},
 {'album_name': 'Say my name',
  'artist_name': 'Nico Spagnoli',
  'music_id': '5EeRnheZ3gYuBjomxX7ojU',
  'music_name': 'Say my name'},
 {'album_name': 'Sweetest Pie',
  'artist_name': 'Dua Lipa',
  'music_id': '7mFj0LlWtEJaEigguaWqYh',
  'music_name': 'Sweetest Pie'},
 {'album_name': 'Planet Her',
  'artist_name': 'Doja Cat',
  'music_id': '3DarAbFujv6eYNliUTyqtz',
  'music_name': 'Kiss Me More (feat. SZA)'}]